---
id: nyankosakana
tags:
- nyanko
- sakana
version: 1.0.0
licenses:
- GPLv2+
- CC BY-SA 3.0
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
